# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(b'1', b'1ero'), (b'2', b'2do'), (b'3', b'3ro'), (b'4', b'4to'), (b'5', b'5to'), (b'6', b'6to'), (b'7', b'7mo')])),
                ('division', models.CharField(choices=[(b'A', b'a'), (b'B', b'b'), (b'C', b'c')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')])),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_alumno', to='SistNotas.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_profesor', to='SistNotas.Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_curso', to='SistNotas.Curso'),
        ),
    ]
