# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0002_auto_20180405_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_profesor',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='id_curso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='materia',
            name='alumnos',
            field=models.ManyToManyField(to='SistNotas.Alumno'),
        ),
    ]
