# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0005_auto_20180405_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesores',
            field=models.ManyToManyField(blank=True, null=True, to='SistNotas.Profesor'),
        ),
    ]
