# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0008_auto_20180405_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alumnos', models.ManyToManyField(blank=True, to='SistNotas.Alumno')),
                ('profesores', models.ManyToManyField(blank=True, to='SistNotas.Profesor')),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='id_materia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_materia', to='SistNotas.Materia'),
            preserve_default=False,
        ),
    ]
