# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0009_auto_20180405_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='id_alumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='id_materia',
            new_name='materia',
        ),
    ]
