# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0010_auto_20180405_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=2),
        ),
    ]
