# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0012_auto_20180410_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='first_name',
            new_name='name',
        ),
    ]
