# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0014_auto_20180410_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistNotas.Student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistNotas.Subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.CharField(choices=[(b'1', b'Uno'), (b'2', b'Dos'), (b'3', b'Tres'), (b'4', b'Cuatro'), (b'5', b'Cinco'), (b'6', b'Seis'), (b'7', b'Siete'), (b'8', b'Ocho'), (b'9', b'Nueve'), (b'10', b'Diez')], max_length=2),
        ),
    ]
