# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistNotas', '0016_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.CharField(choices=[(b'1', b'Uno(1)'), (b'2', b'Dos(2)'), (b'3', b'Tres(3)'), (b'4', b'Cuatro(4)'), (b'5', b'Cinco(5)'), (b'6', b'Seis(6)'), (b'7', b'Siete(7)'), (b'8', b'Ocho(8)'), (b'9', b'Nueve(9)'), (b'10', b'Diez(10)')], max_length=2),
        ),
    ]
